### ISSUE TITLE
behaving wrong when a cell contents contain a value with comma ','

### ISSUE THREAD

**Issue by manikanta-kotha** [AllenZeng/download-csv#2]
```
const downloadCsv = require("download-csv")


const datas = [
  { name: 'test1', score: 1, level: 'Z' },
  { name: 'tes, t, 2', score: 2 },
  { name: 'test3', score: 3 },
  { name: 'test4', score: 4 },
];

const columns = { name: 'Head', score: 'Score' };

downloadCsv(datas, columns);
```

output is like below
![image](https://user-images.githubusercontent.com/10682255/29456777-f6621ef0-8434-11e7-91f3-bec8b76f4de0.png)

**Comment by AllenZeng** [comment]
Thanks for your report.🙂
the csv file(Comma-separated values) separated by commas.
If your source data contains a comma, the downloaded file will go wrong.
So when you download the file, you can convert the comma characters in the data to any other character.

```javascript
'tes, t, 2'.replace(/,/g, '-')
```
